services:
  db:
    image: supabase/postgres:17.6.1.096
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-captionit@1234}
      JWT_SECRET: ${JWT_SECRET:-clave-secreta-captionit-segura-1234}
    volumes:
      - data:/var/lib/postgresql/data
      - ./backend/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s     
      timeout: 5s       
      retries: 10       
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_SERVER: db
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-postgres@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-captionit@1234}
    ports:
      - 8083:80
    depends_on:
      db:
        condition: service_healthy

  postgrest:
    image: postgrest/postgrest
    restart: unless-stopped
    environment:
      PGRST_DB_URI: postgres://authenticator:${POSTGRES_PASSWORD:-captionit@1234}@db:5432/${POSTGRES_DB:-postgres}
      PGRST_DB_SCHEMAS: "public, basic_auth"
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: ${JWT_SECRET:-clave-secreta-captionit-segura-1234}
      PGRST_APP_SETTINGS_JWT_SECRET: ${JWT_SECRET:-clave-secreta-captionit-segura-1234}
      PGRST_APP_SETTINGS_JWT_EXP: ${JWT_EXPIRY:-86400}
      PGRST_SERVER_HOST: 0.0.0.0
    ports:
      - 3000:3000
    command: ["postgrest"]
    depends_on:
      db:
        condition: service_healthy

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8084:8080"
    environment:
      API_URL: http://postgrest:3000/
      
  sse:
    build:
      context: ./backend/sse-service
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: ${POSTGRES_DB:-postgres}
      PGUSER: postgres
      PGPASSWORD: ${POSTGRES_PASSWORD:-captionit@1234}
      PG_CHANNEL: messages_changes
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"

volumes:
  data: