ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE rooms ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION auth_uid() RETURNS int AS $$
  SELECT current_setting('app.settings.jwt_user_id', true)::int;
$$ LANGUAGE sql STABLE;
