-- EXEMPLES D'IMATGES (modality_id = 1)
INSERT INTO templates (content, modality_id) VALUES 
('https://api.memegen.link/images/afraid.png', 1),
('https://api.memegen.link/images/bad.png', 1),
('https://api.memegen.link/images/boat.png', 1),
('https://api.memegen.link/images/both.png', 1),
('https://api.memegen.link/images/bs.png', 1),
('https://api.memegen.link/images/cb.png', 1),
('https://api.memegen.link/images/center.png', 1),
('https://api.memegen.link/images/ch.png', 1),
('https://api.memegen.link/images/chosen.png', 1),
('https://api.memegen.link/images/db.png', 1),
('https://api.memegen.link/images/disastergirl.png', 1),
('https://api.memegen.link/images/doge.png', 1),
('https://api.memegen.link/images/dwight.png', 1),
('https://api.memegen.link/images/elf.png', 1),
('https://api.memegen.link/images/ermg.png', 1),
('https://api.memegen.link/images/facepalm.png', 1),
('https://api.memegen.link/images/fry.png', 1),
('https://api.memegen.link/images/grumpycat.png', 1),
('https://api.memegen.link/images/hagrid.png', 1),
('https://api.memegen.link/images/happening.png', 1),
('https://api.memegen.link/images/harold.png', 1),
('https://api.memegen.link/images/icanhas.png', 1),
('https://api.memegen.link/images/inigo.png', 1),
('https://api.memegen.link/images/ive.png', 1),
('https://api.memegen.link/images/joker.png', 1),
('https://api.memegen.link/images/kermit.png', 1),
('https://api.memegen.link/images/leo.png', 1),
('https://api.memegen.link/images/ll.png', 1),
('https://api.memegen.link/images/morpheus.png', 1),
('https://api.memegen.link/images/older.png', 1),
('https://api.memegen.link/images/saltbae.png', 1),
('https://api.memegen.link/images/sarcasticbear.png', 1),
('https://api.memegen.link/images/spiderman.png', 1),
('https://api.memegen.link/images/success.png', 1),
('https://api.memegen.link/images/aag.png', 1),
('https://api.memegen.link/images/biw.png', 1),
('https://api.memegen.link/images/crazypills.png', 1),
('https://api.memegen.link/images/dodgson.png', 1),
('https://api.memegen.link/images/fine.png', 1),
('https://api.memegen.link/images/gandalf.png', 1),
('https://api.memegen.link/images/jetpack.png', 1),
('https://api.memegen.link/images/sad-obama.png', 1),
('https://api.memegen.link/images/yuno.png', 1);
('https://api.memegen.link/images/wonka.png', 1),
('https://api.memegen.link/images/blb.png', 1),
('https://api.memegen.link/images/patrick.png', 1),
('https://api.memegen.link/images/fwp.png', 1),
('https://api.memegen.link/images/keanu.png', 1),
('https://api.memegen.link/images/stew.png', 1);

-- FRASES PER COMPLETAR (modality_id = 2)
INSERT INTO templates (content, modality_id) VALUES 
('No hay nada mejor para ligar que hablar sobre...', 2),
('Lo que realmente se esconde en el Área 51 es...', 2),
('He decidido que a partir de mañana mi dieta consistirá solo en...', 2),
('El peor regalo que puedes hacer en un cumpleaños es...', 2),
('Lo peor que podrías decir en un funeral es...', 2),
('En mi currículum dice que soy experto en...', 2),
('Lo último que querrías escuchar antes de dormir es...', 2),
('El secreto de la felicidad se resume en una sola palabra: ...', 2),
('Jamás me hubiera imaginado que acabaría comprándome un/a...', 2),
('Si yo fuera presidente del gobierno, la primera ley sería...', 2),
('Si ganara la lotería, lo primero que haría sería comprar...', 2),
('Mi peor pesadilla es quedarme atrapado en un ascensor con...', 2),
('¿Qué hay realmente dentro de las salchichas baratas del súper?', 2),
('El último deseo de un condenado a muerte antes de la silla eléctrica...', 2),
('La próxima película de Disney tratará sobre el romance entre... y...', 2),
('La peor sorpresa que te puedes encontrar en un Kinder Sorpresa es...', 2),
('El peor eslogan para una clínica de abortos sería...', 2),
('La peor forma de morir en un apocalipsis zombie es...', 2),
('El motivo por el cual no me invitan nunca a las cenas familiares es...', 2),
('Lo más turbio que podrías encontrar en el historial de Google de tu abuelo es...', 2),
('La mejor manera de deshacerse de un cadáver sin dejar rastro es...', 2),
('La peor actividad para una excursión de un orfanato es...', 2),
('El motivo por el cual Dios ya no nos habla es...', 2),
('La mejor forma de arruinar una boda en el momento del "sí, quiero" es...', 2),
('La peor pregunta que le puedes hacer a un huérfano es...', 2),
('El motivo real de la Tercera Guerra Mundial será...', 2),
('¿Qué ocurre realmente en un convento durante la noche?', 2),
('¿Qué hace una mujer fuera de la cocina?', 2),
('El verdadero motivo por el cual los negros corren tan rápido es...', 2),
('La ventaja de tener una novia de 6 años es que...', 2),
('¿Qué es lo primero que hace un inmigrante al llegar a España?', 2),
('La razón por la que las mujeres no saben aparcar es...', 2),
('¿Qué es lo último que pasa por la cabeza de un suicida antes de saltar?', 2),
('El truco infalible para que una mujer deje de hablar es...', 2),
('Lo mejor de salir con una chica con Alzheimer es que...', 2),
('El eslogan perfecto para una marca de ropa fabricada por niños es...', 2);